### ISSUE TITLE
IPv6 nodes not matched correctly

### ISSUE THREAD

**Issue by TheGreenkey** [supertassu/laravel-torblock#1]
IPv6 node addresses won't be matched correctly.

For example:
The node I tried your package with has the IP `2a0f:9100:110:a::2` (as output from `$request->ip()`) but the node is listed in the cache as `2A0F:9100:110:A:0:0:0:2`. So every IPv6 Address will be written in normalized and verbose format into the cache therefore the value of `$request->ip()` used in the middleware should also be normalized first. (Theoretically `$request->ips()` should be used, as a request could contain multiple addresses inside the `REMOTE_ADDR` variable (the variable symfony uses in the background))

**Comment by supertassu** [comment]
Thanks for the report. I belive this was fixed in the 1.2.0 release.
